# An RDS endpoint carries an id generated by AWS that does not survive a
# rebuild. Tools that keep the host in their own saved config, like DBeaver,
# would break on every rebuild. The private zone gives each engine a name
# that never changes: mysql.lab.internal, sqlserver.lab.internal.

resource "aws_route53_zone" "internal" {
  name    = var.internal_domain
  comment = "Stable database names - resolves only inside the VPC"

  vpc {
    vpc_id = aws_vpc.main.id
  }
}

resource "aws_route53_record" "database" {
  for_each = aws_db_instance.main

  zone_id = aws_route53_zone.internal.zone_id
  name    = "${each.key}.${var.internal_domain}"
  type    = "CNAME"
  ttl     = 60 # short: the target changes whenever the database is rebuilt
  records = [each.value.address]
}
